baseURL: "https://Mukj1.github.io" 
title: Ruichen Yang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Mukj1's log
          url: log/
          weight: 5 
        - name: Research
          url: papers/
          weight: 2
        - name: About Me
          url: aboutme/
          weight: 1 


params:
    description: "This website hosts Ruichen's research progress, curriculum vitae, and contact information."
    author: Ruichen Yang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["About Me","books","courses","papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ruichen Yang 杨睿辰
          subtitle: "Welcome to my space. I'm an outdoor sports enthusiast (especially cycling), a rock music fan, and a Counter-Strike player. I enjoy making new friends and welcome conversations from all walks of life. Through these communications, we can discover more of the world's intricacies and find joy in the details."
          imageUrl: "avatar.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: About Me
              url: aboutme/
            - name: Research
              url: papers/
            - name: Mukj1's log
              url: log/


    socialIcons:
        - name: CV
          url: Ruichen_CV.pdf
        - name: Email
          url: mailto:jrcyang08@outlook.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=i4R9ZRsAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/Mukj1
        - name: LinkedIn
          url: https://www.linkedin.com/in/ruichen-yang-3094562b3
          

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ruichen Yang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2